In [282]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [283]:
from pathlib import Path

In [284]:
cwd = Path.cwd()

In [285]:
cwd

PosixPath('/workspace')

In [286]:
project_root = cwd.parent if cwd.name == "notebooks" else cwd
print("Project root:", project_root)
for folder in ["data", "notebooks", "src", "reports"]:
    path = project_root / folder
    print(f"\n--- {folder}/ ---")
    if path.exists():
        for file in sorted(path.rglob("*")):
            if file.is_file():
                print(file.relative_to(project_root))
    else:
        print("Folder not found")

Project root: /workspace

--- data/ ---
data/raw/01_data_audit_exploration.ipynb
data/raw/02_CortexHR_AI_ML_Dataset.xlsx
data/raw/02_feature_pipeline.ipynb
data/raw/feature.py

--- notebooks/ ---

--- src/ ---
src/.ipynb_checkpoints/feature-checkpoint.py
src/.ipynb_checkpoints/features-checkpoint.py
src/__pycache__/feature.cpython-312.pyc
src/__pycache__/features.cpython-312.pyc
src/feature.py
src/features.py

--- reports/ ---

In [287]:
project_root = Path("/workspace")
file_path = project_root / "data/raw/02_CortexHR_AI_ML_Dataset.xlsx"
xls = pd.ExcelFile(file_path)
for sheet in xls.sheet_names:
    print("-", sheet)

- README
- data_dictionary
- attrition_dataset
- protected_attributes
- attrition_scoring_2026
- engagement_survey
- performance_reviews
- attendance_monthly_features
- attendance_anomaly_labels
- attendance_daily_examples
- payroll_monthly_features
- payroll_anomaly_labels
- monthly_headcount_history
- workforce_events
- salary_training
- job_descriptions
- resumes
- resume_job_labels
- resume_bias_pairs
- resume_protected_attrs
- chatbot_nlu_training
- chatbot_test_set
- chatbot_responses
- hr_faq
- chatbot_dialogues
- baseline_benchmarks
- anomaly_baselines
- sample_attrition_risk
- sample_anomaly_results
- sample_forecast
- answer_key_planted_dirt
- answer_key_notes

In [288]:
df=pd.read_excel(file_path,sheet_name="attendance_monthly_features")

In [289]:
df

,attendance_feature_id,employee_id,month,department_id,job_level,scheduled_days,present_days,wfh_days,half_days_unpaid,paid_leave_days,unpaid_absence_days,longest_unpaid_streak_days,late_arrivals,avg_hours_worked,overtime_hours,attendance_rate
0,AF-00001,EMP-0002,2025-04-01,D08,4,20,20,18,0,0,0,0,1,8.50,0.0,1.0000
1,AF-00002,EMP-0002,2025-05-01,D08,4,21,20,18,1,0,0,0,2,8.71,0.0,0.9762
2,AF-00003,EMP-0002,2025-06-01,D08,4,21,19,18,1,1,0,0,1,8.25,0.0,0.9286
3,AF-00004,EMP-0002,2025-07-01,D08,4,23,23,22,0,0,0,0,1,8.63,0.0,1.0000
4,AF-00005,EMP-0002,2025-08-01,D08,4,19,19,19,0,0,0,0,1,8.62,0.0,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,AF-07335,EMP-0741,2026-09-01,D01,3,5,5,2,0,0,0,0,1,8.75,0.0,1.0000
7335,AF-07336,EMP-0742,2026-09-01,D04,3,4,4,1,0,0,0,0,0,9.00,0.0,1.0000
7336,AF-07337,EMP-0743,2026-09-01,D09,2,4,3,0,0,1,0,0,0,6.81,2.5,0.7500
7337,AF-07338,EMP-0744,2026-09-01,D01,2,4,4,4,0,0,0,0,0,8.81,0.0,1.0000
7338,AF-07339,EMP-0745,2026-09-01,D06,1,3,3,0,0,0,0,0,0,8.75,0.0,1.0000

In [290]:
df.shape

(7339, 16)

In [291]:
df.dtypes

attendance_feature_id                    str
employee_id                              str
month                         datetime64[us]
department_id                            str
job_level                              int64
scheduled_days                         int64
present_days                           int64
wfh_days                               int64
half_days_unpaid                       int64
paid_leave_days                        int64
unpaid_absence_days                    int64
longest_unpaid_streak_days             int64
late_arrivals                          int64
avg_hours_worked                     float64
overtime_hours                       float64
attendance_rate                      float64
dtype: object

In [292]:
df["employee_id"].nunique()

528

In [293]:
 df["month"].nunique()

18

In [294]:
df.isna().sum()

attendance_feature_id         0
employee_id                   0
month                         0
department_id                 0
job_level                     0
scheduled_days                0
present_days                  0
wfh_days                      0
half_days_unpaid              0
paid_leave_days               0
unpaid_absence_days           0
longest_unpaid_streak_days    0
late_arrivals                 0
avg_hours_worked              0
overtime_hours                0
attendance_rate               0
dtype: int64

In [295]:
df.duplicated(subset=["employee_id","month"]).sum()

np.int64(0)

In [296]:
# validate attendance values

In [297]:
print("Attendance rate outside [0,1]:")
((df["attendance_rate"]<0) | (df["attendance_rate"]>1)).sum()

Attendance rate outside [0,1]:

np.int64(0)

In [298]:
count_columns =[
    "scheduled_days",                
    "present_days",
    "wfh_days",                      
    "half_days_unpaid",
    "paid_leave_days",              
    "unpaid_absence_days",           
    "longest_unpaid_streak_days",    
    "late_arrivals",                 
    "avg_hours_worked",              
    "overtime_hours",
]

In [299]:
#negative values

In [300]:
(df[count_columns]<0).sum()

scheduled_days                0
present_days                  0
wfh_days                      0
half_days_unpaid              0
paid_leave_days               0
unpaid_absence_days           0
longest_unpaid_streak_days    0
late_arrivals                 0
avg_hours_worked              0
overtime_hours                0
dtype: int64

In [301]:
#check whether present days exceed schedules days

In [302]:
(df["present_days"]>df["scheduled_days"]).sum()

np.int64(0)

In [303]:
df["attendance_rate"].describe()

count    7339.000000
mean        0.935503
std         0.124600
min         0.000000
25%         0.913000
50%         1.000000
75%         1.000000
max         1.000000
Name: attendance_rate, dtype: float64

In [304]:
df1=df.copy()

In [305]:
df2=pd.read_excel(file_path,sheet_name="payroll_monthly_features")

In [306]:
df2

,payroll_item_id,run_id,employee_id,month,department_id,role_id,job_level,overtime_eligible,monthly_fixed_gross,payable_days,...,variable_pay,variable_pay_type,gross_pay,pf_employee,esi_employee,professional_tax,tds,other_deductions,total_deductions,net_pay
0,PI-000001,PR-2025-04,EMP-0002,2025-04-01,D08,R047,4,N,144460.0,30.0,...,34670.40,Performance Bonus,179130.40,1800.00,0.0,200,18625.79,0,20625.79,158504.61
1,PI-000002,PR-2025-04,EMP-0004,2025-04-01,D03,R017,3,N,103938.0,30.0,...,56126.52,Performance Bonus,160064.52,1800.00,0.0,200,29517.82,0,31517.82,128546.70
2,PI-000003,PR-2025-04,EMP-0006,2025-04-01,D00,R001,7,N,479009.0,30.0,...,0.00,NaN,479009.00,1800.00,0.0,200,111100.81,0,113100.81,365908.19
3,PI-000004,PR-2025-04,EMP-0011,2025-04-01,D07,R039,1,Y,24041.0,29.5,...,12982.14,Performance Bonus,36969.21,1134.69,0.0,200,0.00,0,1334.69,35634.52
4,PI-000005,PR-2025-04,EMP-0012,2025-04-01,D01,R004,2,N,53915.0,30.0,...,0.00,NaN,53915.00,1800.00,0.0,200,0.00,0,2000.00,51915.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7350,PI-007336,PR-2026-09,EMP-0741,2026-09-01,D01,R006,3,N,121940.0,7.0,...,0.00,NaN,28452.67,1365.73,0.0,200,1784.45,0,3350.18,25102.49
7351,PI-007337,PR-2026-09,EMP-0742,2026-09-01,D04,R024,3,N,120687.0,6.0,...,0.00,NaN,24137.40,1158.60,0.0,0,1490.43,0,2649.03,21488.37
7352,PI-007338,PR-2026-09,EMP-0743,2026-09-01,D09,R051,2,Y,35175.0,6.0,...,0.00,NaN,7880.55,337.68,0.0,0,0.00,0,337.68,7542.87
7353,PI-007339,PR-2026-09,EMP-0744,2026-09-01,D01,R003,2,N,68566.0,6.0,...,0.00,NaN,13713.20,658.22,0.0,0,0.00,0,658.22,13054.98
7354,PI-007340,PR-2026-09,EMP-0745,2026-09-01,D06,R033,1,Y,21217.0,3.0,...,0.00,NaN,2121.70,101.84,0.0,0,0.00,0,101.84,2019.86

In [307]:
df2.head(10)

,payroll_item_id,run_id,employee_id,month,department_id,role_id,job_level,overtime_eligible,monthly_fixed_gross,payable_days,...,variable_pay,variable_pay_type,gross_pay,pf_employee,esi_employee,professional_tax,tds,other_deductions,total_deductions,net_pay
0,PI-000001,PR-2025-04,EMP-0002,2025-04-01,D08,R047,4,N,144460.0,30.0,...,34670.40,Performance Bonus,179130.40,1800.00,0.0,200,18625.79,0,20625.79,158504.61
1,PI-000002,PR-2025-04,EMP-0004,2025-04-01,D03,R017,3,N,103938.0,30.0,...,56126.52,Performance Bonus,160064.52,1800.00,0.0,200,29517.82,0,31517.82,128546.70
2,PI-000003,PR-2025-04,EMP-0006,2025-04-01,D00,R001,7,N,479009.0,30.0,...,0.00,NaN,479009.00,1800.00,0.0,200,111100.81,0,113100.81,365908.19
3,PI-000004,PR-2025-04,EMP-0011,2025-04-01,D07,R039,1,Y,24041.0,29.5,...,12982.14,Performance Bonus,36969.21,1134.69,0.0,200,0.00,0,1334.69,35634.52
4,PI-000005,PR-2025-04,EMP-0012,2025-04-01,D01,R004,2,N,53915.0,30.0,...,0.00,NaN,53915.00,1800.00,0.0,200,0.00,0,2000.00,51915.00
5,PI-000006,PR-2025-04,EMP-0013,2025-04-01,D04,R023,2,N,48514.0,30.0,...,26197.56,Performance Bonus,74711.56,1800.00,0.0,200,0.00,0,2000.00,72711.56
6,PI-000007,PR-2025-04,EMP-0015,2025-04-01,D01,R005,3,N,111986.0,30.0,...,26876.64,Performance Bonus,138862.64,1800.00,0.0,200,11710.71,0,13710.71,125151.93
7,PI-000008,PR-2025-04,EMP-0016,2025-04-01,D01,R003,2,N,71134.0,30.0,...,38412.36,Performance Bonus,109546.36,1800.00,0.0,200,0.00,0,2000.00,107546.36
8,PI-000009,PR-2025-04,EMP-0019,2025-04-01,D03,R015,1,N,32682.0,30.0,...,7843.68,Performance Bonus,40525.68,1568.76,0.0,200,0.00,0,1768.76,38756.92
9,PI-000010,PR-2025-04,EMP-0025,2025-04-01,D01,R003,2,N,59452.0,30.0,...,32104.08,Performance Bonus,91556.08,1800.00,0.0,200,0.00,0,2000.00,89556.08

In [308]:
df2.dtypes

payroll_item_id                   str
run_id                            str
employee_id                       str
month                  datetime64[us]
department_id                     str
role_id                           str
job_level                       int64
overtime_eligible                 str
monthly_fixed_gross           float64
payable_days                  float64
lop_days                      float64
overtime_hours_paid           float64
overtime_pay                  float64
variable_pay                  float64
variable_pay_type                 str
gross_pay                     float64
pf_employee                   float64
esi_employee                  float64
professional_tax                int64
tds                           float64
other_deductions                int64
total_deductions              float64
net_pay                       float64
dtype: object

In [309]:
df2["employee_id"].nunique()

528

In [310]:
 df2["month"].nunique()

18

In [311]:
df2.isna().sum()

payroll_item_id           0
run_id                    0
employee_id               0
month                     0
department_id             0
role_id                   0
job_level                 0
overtime_eligible         0
monthly_fixed_gross       0
payable_days              0
lop_days                  0
overtime_hours_paid       0
overtime_pay              0
variable_pay              0
variable_pay_type      6202
gross_pay                 0
pf_employee               0
esi_employee              0
professional_tax          0
tds                       0
other_deductions          0
total_deductions          0
net_pay                   0
dtype: int64

In [312]:
df2.duplicated(
        subset=["employee_id", "month"]
    ).sum()

np.int64(15)

In [313]:
# variable_pay_type      6202
# Duplicate employee-month combinations 15

In [314]:
duplicate_mask = df2.duplicated(subset=["employee_id", "month"],keep=False)

In [315]:
payroll_duplicates=df2.loc[duplicate_mask].sort_values(["employee_id","month"])

In [316]:
len(payroll_duplicates)

30

In [317]:
 payroll_duplicates[
        [
            "employee_id",
            "month",
            "payroll_item_id",
            "run_id",
            "monthly_fixed_gross",
            "variable_pay",
            "gross_pay",
            "total_deductions",
            "net_pay",] ]

,employee_id,month,payroll_item_id,run_id,monthly_fixed_gross,variable_pay,gross_pay,total_deductions,net_pay
3975,EMP-0012,2026-02-01,PI-003970,PR-2026-02,53915.0,0.0,53915.00,2000.00,51915.00
3976,EMP-0012,2026-02-01,PI-D00007,PR-2026-02,53915.0,0.0,53915.00,2000.00,51915.00
5673,EMP-0092,2026-06-01,PI-005661,PR-2026-06,73903.0,0.0,73903.00,2000.00,71903.00
5674,EMP-0092,2026-06-01,PI-D00015,PR-2026-06,73903.0,0.0,73903.00,2000.00,71903.00
2416,EMP-0112,2025-10-01,PI-002412,PR-2025-10,332694.0,10000.0,342694.00,70570.53,272123.47
2417,EMP-0112,2025-10-01,PI-D00002,PR-2025-10,332694.0,10000.0,342694.00,70570.53,272123.47
4058,EMP-0179,2026-02-01,PI-004052,PR-2026-02,88641.0,0.0,88641.00,2000.00,86641.00
4059,EMP-0179,2026-02-01,PI-D00001,PR-2026-02,88641.0,0.0,88641.00,2000.00,86641.00
496,EMP-0218,2025-05-01,PI-000497,PR-2025-05,178808.0,0.0,178808.00,20865.08,157942.92
497,EMP-0218,2025-05-01,PI-D00008,PR-2025-05,178808.0,0.0,178808.00,20865.08,157942.92
514,EMP-0250,2025-05-01,PI-000514,PR-2025-05,63282.0,0.0,63282.00,2000.00,61282.00
515,EMP-0250,2025-05-01,PI-D00013,PR-2025-05,63282.0,0.0,63282.00,2000.00,61282.00
4576,EMP-0386,2026-03-01,PI-004567,PR-2026-03,61000.0,0.0,57064.51,2000.00,55064.51
4577,EMP-0386,2026-03-01,PI-D00004,PR-2026-03,61000.0,0.0,57064.51,2000.00,55064.51
604,EMP-0408,2025-05-01,PI-000603,PR-2025-05,151737.0,0.0,151737.00,14927.96,136809.04
605,EMP-0408,2025-05-01,PI-D00010,PR-2025-05,151737.0,0.0,151737.00,14927.96,136809.04
1381,EMP-0411,2025-07-01,PI-001378,PR-2025-07,112422.0,0.0,112422.00,8162.83,104259.17
1382,EMP-0411,2025-07-01,PI-D00012,PR-2025-07,112422.0,0.0,112422.00,8162.83,104259.17
4191,EMP-0430,2026-02-01,PI-004184,PR-2026-02,40306.0,0.0,40306.00,2000.00,38306.00
4192,EMP-0430,2026-02-01,PI-D00006,PR-2026-02,40306.0,0.0,40306.00,2000.00,38306.00
5111,EMP-0579,2026-04-01,PI-005101,PR-2026-04,108400.0,0.0,108400.00,4236.00,104164.00
5112,EMP-0579,2026-04-01,PI-D00005,PR-2026-04,108400.0,0.0,108400.00,4236.00,104164.00
1132,EMP-0585,2025-06-01,PI-001130,PR-2025-06,79018.0,0.0,79018.00,2000.00,77018.00
1133,EMP-0585,2025-06-01,PI-D00014,PR-2025-06,79018.0,0.0,79018.00,2000.00,77018.00
5531,EMP-0590,2026-05-01,PI-005520,PR-2026-05,128625.0,0.0,128625.00,10690.50,117934.50
5532,EMP-0590,2026-05-01,PI-D00009,PR-2026-05,128625.0,0.0,128625.00,10690.50,117934.50
4328,EMP-0622,2026-02-01,PI-004320,PR-2026-02,43222.0,0.0,43222.00,2000.00,41222.00
4329,EMP-0622,2026-02-01,PI-D00011,PR-2026-02,43222.0,0.0,43222.00,2000.00,41222.00
6451,EMP-0691,2026-07-01,PI-006438,PR-2026-07,34108.0,0.0,38207.52,1837.16,36370.36
6452,EMP-0691,2026-07-01,PI-D00003,PR-2026-07,34108.0,0.0,38207.52,1837.16,36370.36

In [321]:
duplicate_df = df2.loc[duplicate_mask]

In [322]:
duplicate_df.duplicated(
        subset=[
            "employee_id",
            "month",
            "run_id",
            "monthly_fixed_gross",
            "gross_pay",
            "total_deductions",
            "net_pay",
        ],
        keep=False
    ).sum()

np.int64(30)

In [323]:
print("\nPayroll item ID prefixes:")

duplicate_df["payroll_item_id"].str.extract(r"^(PI-[A-Z]+)")[0].value_counts(dropna=False)

Payroll item ID prefixes:

0
NaN     15
PI-D    15
Name: count, dtype: int64

In [324]:
compare_columns = [
    "employee_id",
    "month",
    "run_id",
    "monthly_fixed_gross",
    "gross_pay",
    "total_deductions",
    "net_pay",
]
duplicate_df[compare_columns + ["payroll_item_id"]].sort_values(["employee_id", "month"])

,employee_id,month,run_id,monthly_fixed_gross,gross_pay,total_deductions,net_pay,payroll_item_id
3975,EMP-0012,2026-02-01,PR-2026-02,53915.0,53915.00,2000.00,51915.00,PI-003970
3976,EMP-0012,2026-02-01,PR-2026-02,53915.0,53915.00,2000.00,51915.00,PI-D00007
5673,EMP-0092,2026-06-01,PR-2026-06,73903.0,73903.00,2000.00,71903.00,PI-005661
5674,EMP-0092,2026-06-01,PR-2026-06,73903.0,73903.00,2000.00,71903.00,PI-D00015
2416,EMP-0112,2025-10-01,PR-2025-10,332694.0,342694.00,70570.53,272123.47,PI-002412
2417,EMP-0112,2025-10-01,PR-2025-10,332694.0,342694.00,70570.53,272123.47,PI-D00002
4058,EMP-0179,2026-02-01,PR-2026-02,88641.0,88641.00,2000.00,86641.00,PI-004052
4059,EMP-0179,2026-02-01,PR-2026-02,88641.0,88641.00,2000.00,86641.00,PI-D00001
496,EMP-0218,2025-05-01,PR-2025-05,178808.0,178808.00,20865.08,157942.92,PI-000497
497,EMP-0218,2025-05-01,PR-2025-05,178808.0,178808.00,20865.08,157942.92,PI-D00008
514,EMP-0250,2025-05-01,PR-2025-05,63282.0,63282.00,2000.00,61282.00,PI-000514
515,EMP-0250,2025-05-01,PR-2025-05,63282.0,63282.00,2000.00,61282.00,PI-D00013
4576,EMP-0386,2026-03-01,PR-2026-03,61000.0,57064.51,2000.00,55064.51,PI-004567
4577,EMP-0386,2026-03-01,PR-2026-03,61000.0,57064.51,2000.00,55064.51,PI-D00004
604,EMP-0408,2025-05-01,PR-2025-05,151737.0,151737.00,14927.96,136809.04,PI-000603
605,EMP-0408,2025-05-01,PR-2025-05,151737.0,151737.00,14927.96,136809.04,PI-D00010
1381,EMP-0411,2025-07-01,PR-2025-07,112422.0,112422.00,8162.83,104259.17,PI-001378
1382,EMP-0411,2025-07-01,PR-2025-07,112422.0,112422.00,8162.83,104259.17,PI-D00012
4191,EMP-0430,2026-02-01,PR-2026-02,40306.0,40306.00,2000.00,38306.00,PI-004184
4192,EMP-0430,2026-02-01,PR-2026-02,40306.0,40306.00,2000.00,38306.00,PI-D00006
5111,EMP-0579,2026-04-01,PR-2026-04,108400.0,108400.00,4236.00,104164.00,PI-005101
5112,EMP-0579,2026-04-01,PR-2026-04,108400.0,108400.00,4236.00,104164.00,PI-D00005
1132,EMP-0585,2025-06-01,PR-2025-06,79018.0,79018.00,2000.00,77018.00,PI-001130
1133,EMP-0585,2025-06-01,PR-2025-06,79018.0,79018.00,2000.00,77018.00,PI-D00014
5531,EMP-0590,2026-05-01,PR-2026-05,128625.0,128625.00,10690.50,117934.50,PI-005520
5532,EMP-0590,2026-05-01,PR-2026-05,128625.0,128625.00,10690.50,117934.50,PI-D00009
4328,EMP-0622,2026-02-01,PR-2026-02,43222.0,43222.00,2000.00,41222.00,PI-004320
4329,EMP-0622,2026-02-01,PR-2026-02,43222.0,43222.00,2000.00,41222.00,PI-D00011
6451,EMP-0691,2026-07-01,PR-2026-07,34108.0,38207.52,1837.16,36370.36,PI-006438
6452,EMP-0691,2026-07-01,PR-2026-07,34108.0,38207.52,1837.16,36370.36,PI-D00003

In [327]:

### Payroll Data Quality Findings

# **Dataset:** `payroll_monthly_features`
# **Records:** 7,355 rows across 528 employees and 18 months.
# **Duplicate employee-month pairs:** 15.
# **Verification:** All 15 pairs have matching values for `run_id`, `monthly_fixed_gross`, `gross_pay`, `total_deductions`, and `net_pay`.
# **Finding:** The records appear to be duplicate payroll entries with different `payroll_item_id` values. Their business meaning must be confirmed before deletion.
# **Missing values:** `variable_pay_type` contains 6,202 missing values. These may represent records without a variable-pay type; investigate before imputing.
# **Action:** Preserve the original data. Resolve duplicate records and missing-value treatment before aggregating payroll features for modeling.

In [328]:
compare_columns = [
    col for col in duplicate_df.columns
    if col != "payroll_item_id"
]

all_columns_check = (
    duplicate_df
    .groupby(["employee_id", "month"])[compare_columns]
    .nunique()
)

different_pairs = (
    (all_columns_check > 1)
    .any(axis=1)
)

print("Pairs checked:", len(all_columns_check))
print("Pairs differing in any other column:", different_pairs.sum())

Pairs checked: 15
Pairs differing in any other column: 0

In [330]:


# - Total records: 7,355
# - Unique employees: 528
# - Months covered: 18 (April 2025–September 2026)
# - Duplicate employee-month pairs: 15
# - Verification: All 15 pairs match across every column except `payroll_item_id`.
# - Finding: These records are suspected duplicate payroll entries with different identifiers.
# - Missing values: `variable_pay_type` has 6,202 missing values (approximately 84.3%).
# - Treatment: Preserve the raw dataset. Investigate the meaning of duplicate records and missing variable-pay types before transforming the derived dataset.

In [331]:
#checking the missing value menaing

In [332]:
print("Missing variable_pay_type:")
display(
    df2.loc[
        df2["variable_pay_type"].isna(),
        ["monthly_fixed_gross", "variable_pay", "gross_pay", "variable_pay_type"]
    ].head(10)
)
print("\nVariable pay summary:")
display(df2["variable_pay"].describe())
print(
    "\nMissing type with zero variable pay:",
    (
        df2["variable_pay_type"].isna()
        & df2["variable_pay"].eq(0)
    ).sum()
)
print(
    "Missing type with nonzero variable pay:",
    (
        df2["variable_pay_type"].isna()
        & df2["variable_pay"].ne(0)
    ).sum()
)

Missing variable_pay_type:

    monthly_fixed_gross  variable_pay  gross_pay variable_pay_type
2              479009.0           0.0  479009.00               NaN
4               53915.0           0.0   53915.00               NaN
13              28343.0           0.0   29841.91               NaN
25             383885.0           0.0  383885.00               NaN
37              43882.0           0.0   43882.00               NaN
38              55212.0           0.0   55212.00               NaN
40              69709.0           0.0   69709.00               NaN
41              29872.0           0.0   33031.54               NaN
48              26542.0           0.0   26542.00               NaN
54              94081.0           0.0   94081.00               NaN

Variable pay summary:

count      7355.000000
mean       8117.823025
std       33442.685466
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      451936.640000
Name: variable_pay, dtype: float64

Missing type with zero variable pay: 6202
Missing type with nonzero variable pay: 0

In [ ]:

### Missing Variable Pay Type — Finding and Treatment

- `variable_pay_type` has 6,202 missing values (approximately 84.3%).
- All 6,202 records have `variable_pay = 0`.
- No records with nonzero variable pay have a missing type.
- Interpretation: Missing types are consistent with months where no variable pay was paid.
- Treatment: In the derived dataset, fill missing `variable_pay_type` values with `"None"`. Preserve the original workbook and column unchanged.
- Limitation: This interpretation is based on the observed data and should be confirmed against the data dictionary if a definition is available.

In [333]:
df2_clean=df2.copy()
df2_clean["variable_pay_type"]=(df2_clean["variable_pay_type"].fillna("None"))

In [334]:
df2["variable_pay_type"].isna().sum()

np.int64(6202)

In [335]:
 df2_clean["variable_pay_type"].isna().sum()

np.int64(0)

In [336]:
df2_clean["variable_pay_type"].value_counts(dropna=False)

variable_pay_type
None                 6202
Performance Bonus     518
Festival Bonus        356
Sales Incentive       234
Spot Award             45
Name: count, dtype: int64

In [337]:
#handling the 15 payroll pairs duplicate

In [338]:
# df2_clean = df2_clean.drop_duplicates(subset=["employee_id", "month"],keep="first").copy()

In [339]:
 # len(df2)

In [75]:
# len(df2_clean)

7340

In [340]:
# df2_clean.duplicated(subset=["employee_id", "month"]).sum()

In [341]:
payroll_dictionary = dictionary[
    (dictionary["sheet"] == "payroll_monthly_features")
    & (
        dictionary["column"].isin([
            "payroll_item_id",
            "employee_id",
            "month",
            "run_id",
            "variable_pay",
            "variable_pay_type",
            "gross_pay",
            "net_pay"
        ])
    )
]

display(
    payroll_dictionary[
        ["column", "data_type", "description", "null_count", "example"]
    ]
)

,column,data_type,description,null_count,example
126,payroll_item_id,text,Unique id of one employee-month pay calculation.,0,PI-000001
127,run_id,text,Payroll run id (PR-YYYY-MM).,0,PR-2025-04
128,employee_id,text,Unique employee code (EMP-0001 ...). Same code...,0,EMP-0002
129,month,date,Month (first day).,0,2025-04-01
139,variable_pay,decimal,"Bonus, incentive or award paid in the month.",0,34670.4
140,variable_pay_type,text,"Performance Bonus, Sales Incentive, Festival B...",6202,Performance Bonus
141,gross_pay,decimal,Earned fixed pay + overtime + variable pay.,0,179130.4
148,net_pay,decimal,Take-home pay = gross pay minus total deductions.,0,158504.61

In [ ]:

### Payroll Data Dictionary Review and Cleaning Decisions

- `payroll_item_id`: Unique identifier for an employee-month pay calculation. Excluded from model inputs.
- `employee_id`: Retained for joins and employee-level grouping; excluded from model inputs.
- `month`: Retained for temporal filtering and aggregation; excluded as a raw model input.
- `run_id`: Payroll-run identifier; excluded from model inputs.
- Duplicate employee-month pairs: 15 pairs were identified. All matched across every column except `payroll_item_id`. These records are preserved and flagged as potential payroll anomalies rather than deleted.
- `variable_pay_type`: 6,202 missing values were found. Every missing-type record has zero `variable_pay`. In the derived dataset, missing types are represented as `"None"`.
- Source preservation: The original workbook is unchanged. All transformations are applied to derived DataFrames.
- Temporal safety: Payroll records must be filtered to the relevant observation period before generating attrition features.

In [342]:
df2_clean = df2.copy()

df2_clean["variable_pay_type"] = (
    df2_clean["variable_pay_type"].fillna("None")
)

print("Raw payroll rows:", len(df2))
print("Derived payroll rows:", len(df2_clean))
print(
    "Missing variable_pay_type after cleaning:",
    df2_clean["variable_pay_type"].isna().sum()
)
print(
    "Duplicate employee-month pairs preserved:",
    df2_clean.duplicated(
        subset=["employee_id", "month"],
        keep=False
    ).sum()
)

Raw payroll rows: 7355
Derived payroll rows: 7355
Missing variable_pay_type after cleaning: 0
Duplicate employee-month pairs preserved: 30

In [ ]:
#check Before adding the datasets

In [345]:
df = pd.read_excel(
    file_path,
    sheet_name="attrition_dataset"
)

In [346]:
df

,row_id,employee_id,observation_date,department_id,role_id,job_level,work_location,work_mode,employment_type,highest_education,...,paid_leave_days_6m,dept_attrition_rate_prior_12m,left_within_12m,voluntary_left_within_12m,source,exit_date,resignation_date,exit_reason,exit_interview_done,fnf_settlement_amount
0,1,EMP-0002,2025-09-30,D08,R047,4,Pune,Remote,Permanent,B.E. Computer Science,...,5,0.2353,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
1,2,EMP-0004,2025-09-30,D03,R017,3,Erode,Hybrid,Permanent,MCA,...,4,0.0556,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2,3,EMP-0011,2025-09-30,D07,R039,1,Kochi,Hybrid,Permanent,M.A. Social Work,...,7,0.0000,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
3,4,EMP-0012,2025-09-30,D01,R004,2,Chennai,Onsite,Permanent,B.Tech Information Technology,...,8,0.1448,1,1,master_employee_snapshot,2026-04-23,2026-03-24,Work-Life Balance,Y,117098.85
4,5,EMP-0013,2025-09-30,D04,R023,2,Chennai,Onsite,Permanent,B.E. Mechanical,...,7,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2384,2385,EMP-0238,2025-09-30,D01,R004,2,Chennai,Remote,Permanent,M.Tech,...,18,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2385,2386,EMP-0483,2025-09-30,D09,R053,4,Bengaluru,Onsite,Permanent,MBA,...,1,0.2069,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2386,2387,EMP-0060,2025-09-30,D01,R006,3,Bengaluru,Hybrid,Permanent,MCA,...,1,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2387,2388,EMP-0237,2025-09-30,D07,R040,2,Chennai,Remote,Permanent,B.Sc,...,9,0.0000,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2388,2389,EMP-0570,2025-09-30,D04,R024,3,Bengaluru,Hybrid,Permanent,B.E. Mechanical,...,5,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN

In [347]:
df.columns.tolist()

['row_id',
 'employee_id',
 'observation_date',
 'department_id',
 'role_id',
 'job_level',
 'work_location',
 'work_mode',
 'employment_type',
 'highest_education',
 'tenure_months',
 'total_experience_years',
 'previous_employers_count',
 'commute_distance_km',
 'annual_fixed_pay',
 'comp_ratio',
 'raises_received',
 'last_raise_pct',
 'months_since_last_raise',
 'promotions_received',
 'months_since_last_promotion',
 'internal_transfers',
 'last_performance_rating',
 'last_engagement_score',
 'manager_changes_12m',
 'training_hours_12m',
 'attendance_rate_3m',
 'late_arrivals_3m',
 'avg_overtime_hours_per_month_3m',
 'avg_hours_worked_3m',
 'wfh_share_3m',
 'unpaid_leave_days_6m',
 'paid_leave_days_6m',
 'dept_attrition_rate_prior_12m',
 'left_within_12m',
 'voluntary_left_within_12m',
 'source',
 'exit_date',
 'resignation_date',
 'exit_reason',
 'exit_interview_done',
 'fnf_settlement_amount']

In [348]:
 df["employee_id"].nunique()

2383

In [349]:
df.duplicated(subset=["employee_id", "observation_date"]).sum()

np.int64(6)

In [350]:
print("\nObservation date range:")
df["observation_date"].min()

Observation date range:

Timestamp('2021-01-01 00:00:00')

In [351]:
df["observation_date"].max()

Timestamp('2025-09-30 00:00:00')

In [352]:
# Load the main attrition dataset
df = pd.read_excel(
    excel_path,
    sheet_name="attrition_dataset"
)

print("Attrition dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nObservation date range:")
print(df["observation_date"].min())
print(df["observation_date"].max())

print("\nUnique employees:", df["employee_id"].nunique())
print("Duplicate employee-date rows:",
      df.duplicated(
          subset=["employee_id", "observation_date"]
      ).sum())

Attrition dataset shape: (2389, 42)

Columns:
['row_id', 'employee_id', 'observation_date', 'department_id', 'role_id', 'job_level', 'work_location', 'work_mode', 'employment_type', 'highest_education', 'tenure_months', 'total_experience_years', 'previous_employers_count', 'commute_distance_km', 'annual_fixed_pay', 'comp_ratio', 'raises_received', 'last_raise_pct', 'months_since_last_raise', 'promotions_received', 'months_since_last_promotion', 'internal_transfers', 'last_performance_rating', 'last_engagement_score', 'manager_changes_12m', 'training_hours_12m', 'attendance_rate_3m', 'late_arrivals_3m', 'avg_overtime_hours_per_month_3m', 'avg_hours_worked_3m', 'wfh_share_3m', 'unpaid_leave_days_6m', 'paid_leave_days_6m', 'dept_attrition_rate_prior_12m', 'left_within_12m', 'voluntary_left_within_12m', 'source', 'exit_date', 'resignation_date', 'exit_reason', 'exit_interview_done', 'fnf_settlement_amount']

Observation date range:
2021-01-01 00:00:00
2025-09-30 00:00:00

Unique employees: 2383
Duplicate employee-date rows: 6

In [93]:
# Check monthly data coverage
for name, data in [
    ("Attrition", df),
    ("Attendance", df1),
    ("Payroll", df2)
]:
    print(f"\n{name}")
    print("Rows:", len(data))
    print("Unique employees:", data["employee_id"].nunique())
    print("Start date:", (
        data["observation_date"].min()
        if "observation_date" in data.columns
        else data["month"].min()
    ))
    print("End date:", (
        data["observation_date"].max()
        if "observation_date" in data.columns
        else data["month"].max()
    ))

Attrition
Rows: 2389
Unique employees: 2383
Start date: 2021-01-01 00:00:00
End date: 2025-09-30 00:00:00

Attendance
Rows: 7339
Unique employees: 528
Start date: 2025-04-01 00:00:00
End date: 2026-09-01 00:00:00

Payroll
Rows: 7355
Unique employees: 528
Start date: 2025-04-01 00:00:00
End date: 2026-09-01 00:00:00

In [ ]:
# The monthly tables start much later than the attrition observations. We also need to avoid using months after an employee's observation date.

In [353]:
# Employee coverage across datasets
attrition_employees = set(df["employee_id"])
attendance_employees = set(df1["employee_id"])
payroll_employees = set(df2["employee_id"])

print("Attrition employees:", len(attrition_employees))
print("Attendance employees:", len(attendance_employees))
print("Payroll employees:", len(payroll_employees))

print(
    "Attrition employees present in attendance:",
    len(attrition_employees & attendance_employees)
)
print(
    "Attrition employees present in payroll:",
    len(attrition_employees & payroll_employees)
)
print(
    "Employees present in all three:",
    len(attrition_employees & attendance_employees & payroll_employees)
)

# How many attrition observations occur during the monthly-data period?
monthly_start = min(df1["month"].min(), df2["month"].min())

print("\nMonthly data starts:", monthly_start)
print(
    "Attrition observations on/after monthly data starts:",
    (df["observation_date"] >= monthly_start).sum()
)

Attrition employees: 2383
Attendance employees: 528
Payroll employees: 528
Attrition employees present in attendance: 383
Attrition employees present in payroll: 383
Employees present in all three: 383

Monthly data starts: 2025-04-01 00:00:00
Attrition observations on/after monthly data starts: 389

In [354]:

# Check whether each attrition observation has monthly history available
attendance_counts = (
    df1[df1["month"] <= df1["month"].max()]
    .groupby("employee_id")["month"]
    .nunique()
)

payroll_counts = (
    df2[df2["month"] <= df2["month"].max()]
    .groupby("employee_id")["month"]
    .nunique()
)

print("Attendance months per employee:")
print(attendance_counts.describe())

print("\nPayroll months per employee:")
print(payroll_counts.describe())

print("\nObservation dates among overlapping employees:")
overlap = df[df["employee_id"].isin(attendance_employees)].copy()
print(overlap["observation_date"].value_counts().sort_index().tail(10))

Attendance months per employee:
count    528.000000
mean      13.899621
std        5.885640
min        1.000000
25%        9.000000
50%       18.000000
75%       18.000000
max       18.000000
Name: month, dtype: float64

Payroll months per employee:
count    528.000000
mean      13.901515
std        5.884221
min        1.000000
25%        9.750000
50%       18.000000
75%       18.000000
max       18.000000
Name: month, dtype: float64

Observation dates among overlapping employees:
observation_date
2025-09-30    389
Name: count, dtype: int64

In [355]:
# Check the valid historical months

In [356]:
# September 30, 2025 observation cutoff
cutoff = pd.Timestamp("2025-09-30")

attendance_before_cutoff = df1[df1["month"] <= cutoff]
payroll_before_cutoff = df2[df2["month"] <= cutoff]

print("Attendance rows on/before cutoff:", len(attendance_before_cutoff))
print("Payroll rows on/before cutoff:", len(payroll_before_cutoff))

print(
    "Attendance month range:",
    attendance_before_cutoff["month"].min(),
    "to",
    attendance_before_cutoff["month"].max()
)

print(
    "Payroll month range:",
    payroll_before_cutoff["month"].min(),
    "to",
    payroll_before_cutoff["month"].max()
)

print(
    "Attendance months available:",
    attendance_before_cutoff["month"].nunique()
)

print(
    "Payroll months available:",
    payroll_before_cutoff["month"].nunique()
)

Attendance rows on/before cutoff: 2354
Payroll rows on/before cutoff: 2359
Attendance month range: 2025-04-01 00:00:00 to 2025-09-01 00:00:00
Payroll month range: 2025-04-01 00:00:00 to 2025-09-01 00:00:00
Attendance months available: 6
Payroll months available: 6

In [357]:
from pathlib import Path

print("Project root:", Path.cwd())

for file in [
    "src/features.py",
    "02_feature_pipeline.ipynb",
    "requirements.txt",
    "reports"
]:
    path = Path(file)
    print(f"{file}: {'EXISTS' if path.exists() else 'MISSING'}")

Project root: /workspace
src/features.py: EXISTS
02_feature_pipeline.ipynb: EXISTS
requirements.txt: EXISTS
reports: EXISTS

In [358]:
# Feature Pipeline

In [359]:
import pandas as pd
from pathlib import Path

print("Working directory:", Path.cwd())
print("Feature file exists:", Path("src/feature.py").exists())

Working directory: /workspace
Feature file exists: True

In [362]:
# from pathlib import Path
# feature_code = '''import pandas as pd


# def add_attrition_features(df: pd.DataFrame) -> pd.DataFrame:
    # """Create engineered features for the attrition dataset."""
    # df = df.copy()

    # df["tenure_years"] = df["tenure_months"] / 12

    # df["raise_overdue"] = (
        # df["months_since_last_raise"] > 12
    # ).astype("int8")

    # df["attendance_gap"] = 1 - df["attendance_rate_3m"]

    # df["unpaid_per_month"] = df["unpaid_leave_days_6m"] / 6

    # df["overtime_load"] = (
        # df["avg_overtime_hours_per_month_3m"]
    # )

    # return df

# Path("src/feature.py").write_text(feature_code)
# print("Saved feature functions to src/feature.py")

In [363]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path("src").resolve()))

from feature import add_attrition_features

print("Feature function imported successfully!")

Feature function imported successfully!

In [364]:
#  feature Engineering

In [365]:
df_features = add_attrition_features(df)

In [366]:
df.shape

(2389, 42)

In [367]:
df_features.shape

(2389, 47)

In [368]:
new_features = [
    "tenure_years",
    "raise_overdue",
    "attendance_gap",
    "unpaid_per_month",
    "overtime_load"
]
df_features[new_features].head()

,tenure_years,raise_overdue,attendance_gap,unpaid_per_month,overtime_load
0,13.666667,0,0.0781,0.333333,0.00
1,13.500000,0,0.0312,0.166667,0.00
2,12.833333,0,0.0547,0.166667,4.33
3,12.666667,0,0.0625,0.000000,0.00
4,12.666667,0,0.1094,0.000000,0.00

In [369]:
new_features = [
    "tenure_years",
    "raise_overdue",
    "attendance_gap",
    "unpaid_per_month",
    "overtime_load"
]

# Check missing values
print("Missing values:")
display(df_features[new_features].isna().sum().to_frame("missing_count"))

# Check descriptive statistics
print("Feature statistics:")
display(df_features[new_features].describe().T)

# Check invalid values
print("Invalid-value checks:")
print(
    "Negative tenure:",
    (df_features["tenure_years"] < 0).sum()
)
print(
    "Raise overdue values outside 0/1:",
    (~df_features["raise_overdue"].isin([0, 1])).sum()
)
print(
    "Attendance gap outside [0, 1]:",
    (
        (df_features["attendance_gap"] < 0) |
        (df_features["attendance_gap"] > 1)
    ).sum()
)
print(
    "Negative unpaid per month:",
    (df_features["unpaid_per_month"] < 0).sum()
)
print(
    "Negative overtime load:",
    (df_features["overtime_load"] < 0).sum()
)

Missing values:

                  missing_count
tenure_years                  4
raise_overdue                 0
attendance_gap                2
unpaid_per_month              0
overtime_load                 0

Feature statistics:

,count,mean,std,min,25%,50%,75%,max
tenure_years,2385.0,3.153739,2.283481,0.0,1.5000,2.583333,4.250000,13.666667
raise_overdue,2389.0,0.331101,0.470708,0.0,0.0000,0.000000,1.000000,1.000000
attendance_gap,2387.0,0.089713,0.047036,0.0,0.0625,0.087200,0.112900,0.796900
unpaid_per_month,2389.0,0.234861,0.238213,0.0,0.0000,0.166667,0.333333,2.000000
overtime_load,2389.0,2.168690,5.334152,0.0,0.0000,0.000000,0.000000,50.000000

Invalid-value checks:
Negative tenure: 0
Raise overdue values outside 0/1: 0
Attendance gap outside [0, 1]: 0
Negative unpaid per month: 0
Negative overtime load: 0

In [370]:
# Inspect the four negative-tenure records

In [371]:
df_features.loc[df_features["tenure_years"] < 0,
        [
            "employee_id",
            "observation_date",
            "tenure_months",
            "total_experience_years",
            "tenure_years"
        ]
    ]

Empty DataFrame
Columns: [employee_id, observation_date, tenure_months, total_experience_years, tenure_years]
Index: []

In [372]:
# Inspect the two invalid attendance-gap records

In [373]:
    df_features.loc[
        ~df_features["attendance_gap"].between(0, 1),
        [
            "employee_id",
            "observation_date",
            "attendance_rate_3m",
            "attendance_gap"
        ]
    ]

     employee_id observation_date  attendance_rate_3m  attendance_gap
430    HIST-0048       2023-04-08                 NaN             NaN
1233   HIST-0851       2024-03-26                 NaN             NaN

In [374]:
import importlib
import feature

importlib.reload(feature)
df_features = feature.add_attrition_features(df)

print("Rows preserved:", len(df_features) == len(df))
print("Negative tenure remaining:", (df_features["tenure_years"] < 0).sum())
print(
    "Invalid attendance gaps remaining:",
    (~df_features["attendance_gap"].dropna().between(0, 1)).sum()
)

Rows preserved: True
Negative tenure remaining: 0
Invalid attendance gaps remaining: 0

In [375]:
#tarfet column

In [376]:
target ="left_within_12m"

In [377]:
target in df_features.columns

True

In [378]:
df_features[target].value_counts(dropna=False).to_frame("count")

                 count
left_within_12m
0                 2040
1                  349

In [379]:
print("Total missing values:", df_features.isna().sum().sum())

missing_summary = (
    df_features.isna()
    .sum()
    .loc[lambda s: s > 0]
    .sort_values(ascending=False)
    .to_frame("missing_count")
)

display(missing_summary)

Total missing values: 12681

                             missing_count
resignation_date                      2068
exit_date                             2040
exit_reason                           2040
exit_interview_done                   2040
fnf_settlement_amount                 2040
months_since_last_promotion           1459
last_engagement_score                  528
last_raise_pct                         202
last_performance_rating                182
commute_distance_km                     55
highest_education                       15
tenure_months                            4
tenure_years                             4
attendance_rate_3m                       2
attendance_gap                           2

In [380]:
leakage_columns = [
    "voluntary_left_within_12m",
    "exit_date",
    "resignation_date",
    "exit_reason",
    "exit_interview_done",
    "fnf_settlement_amount"
]

print("Leakage columns present:")
print([col for col in leakage_columns if col in df_features.columns])

Leakage columns present:
['voluntary_left_within_12m', 'exit_date', 'resignation_date', 'exit_reason', 'exit_interview_done', 'fnf_settlement_amount']

In [381]:
excluded_columns = [
    "row_id",
    "employee_id",
    "observation_date",
    "source",
    "voluntary_left_within_12m",
    "exit_date",
    "resignation_date",
    "exit_reason",
    "exit_interview_done",
    "fnf_settlement_amount"
]

In [382]:
X=df_features.drop(columns=[target]+ excluded_columns, errors="ignore")

In [383]:
y=df_features[target].copy()

In [384]:
X.shape

(2389, 36)

In [385]:
y.shape

(2389,)

target in X.columns

In [386]:
#separate numeric and caterogical columns

In [387]:
numeric_columns=X.select_dtypes(include="number").columns.tolist()

In [388]:
categorical_columns=X.select_dtypes(include=["object", "category", "bool","str"]).columns.tolist()

In [389]:
 len(numeric_columns)

30

In [390]:
numeric_columns

['job_level',
 'tenure_months',
 'total_experience_years',
 'previous_employers_count',
 'commute_distance_km',
 'annual_fixed_pay',
 'comp_ratio',
 'raises_received',
 'last_raise_pct',
 'months_since_last_raise',
 'promotions_received',
 'months_since_last_promotion',
 'internal_transfers',
 'last_performance_rating',
 'last_engagement_score',
 'manager_changes_12m',
 'training_hours_12m',
 'attendance_rate_3m',
 'late_arrivals_3m',
 'avg_overtime_hours_per_month_3m',
 'avg_hours_worked_3m',
 'wfh_share_3m',
 'unpaid_leave_days_6m',
 'paid_leave_days_6m',
 'dept_attrition_rate_prior_12m',
 'tenure_years',
 'raise_overdue',
 'attendance_gap',
 'unpaid_per_month',
 'overtime_load']

In [391]:
len(categorical_columns)

6

In [392]:
categorical_columns

['department_id',
 'role_id',
 'work_location',
 'work_mode',
 'employment_type',
 'highest_education']

In [393]:
len(numeric_columns) + len(categorical_columns)

36

In [394]:
df.head(20)

,row_id,employee_id,observation_date,department_id,role_id,job_level,work_location,work_mode,employment_type,highest_education,...,paid_leave_days_6m,dept_attrition_rate_prior_12m,left_within_12m,voluntary_left_within_12m,source,exit_date,resignation_date,exit_reason,exit_interview_done,fnf_settlement_amount
0,1,EMP-0002,2025-09-30,D08,R047,4,Pune,Remote,Permanent,B.E. Computer Science,...,5,0.2353,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
1,2,EMP-0004,2025-09-30,D03,R017,3,Erode,Hybrid,Permanent,MCA,...,4,0.0556,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
2,3,EMP-0011,2025-09-30,D07,R039,1,Kochi,Hybrid,Permanent,M.A. Social Work,...,7,0.0000,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
3,4,EMP-0012,2025-09-30,D01,R004,2,Chennai,Onsite,Permanent,B.Tech Information Technology,...,8,0.1448,1,1,master_employee_snapshot,2026-04-23,2026-03-24,Work-Life Balance,Y,117098.85
4,5,EMP-0013,2025-09-30,D04,R023,2,Chennai,Onsite,Permanent,B.E. Mechanical,...,7,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
5,6,EMP-0015,2025-09-30,D01,R005,3,Coimbatore,Remote,Permanent,MCA,...,0,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
6,7,EMP-0016,2025-09-30,D01,R003,2,Chennai,Remote,Permanent,B.E. Computer Science,...,0,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
7,8,EMP-0019,2025-09-30,D03,R015,1,Bengaluru,Hybrid,Permanent,MCA,...,3,0.0556,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
8,9,EMP-0025,2025-09-30,D01,R003,2,Bengaluru,Hybrid,Permanent,MCA,...,15,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
9,10,EMP-0026,2025-09-30,D04,R025,4,Bengaluru,Hybrid,Permanent,MBA,...,6,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
10,11,EMP-0029,2025-09-30,D04,R024,3,Coimbatore,Hybrid,Permanent,B.Com,...,1,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
11,12,EMP-0030,2025-09-30,D04,R024,3,Pune,Onsite,Permanent,B.Com,...,1,0.2051,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
12,13,EMP-0031,2025-09-30,D09,R051,2,Chennai,Hybrid,Permanent,B.E. Electronics,...,7,0.2069,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
13,14,EMP-0032,2025-09-30,D01,R004,2,Bengaluru,Hybrid,Permanent,MCA,...,3,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
14,15,EMP-0034,2025-09-30,D03,R015,1,Bengaluru,Hybrid,Permanent,M.Sc Statistics,...,18,0.0556,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
15,16,EMP-0038,2025-09-30,D09,R053,4,Bengaluru,Remote,Permanent,B.Sc,...,6,0.2069,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
16,17,EMP-0040,2025-09-30,D01,R006,3,Mumbai,Remote,Permanent,B.Sc Computer Science,...,1,0.1448,1,1,master_employee_snapshot,2026-05-04,2026-03-05,Work-Life Balance,Y,172960.13
17,18,EMP-0041,2025-09-30,D07,R039,1,Chennai,Onsite,Permanent,MBA HR,...,12,0.0000,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
18,19,EMP-0045,2025-09-30,D01,R006,3,Delhi NCR,Onsite,Permanent,MCA,...,9,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN
19,20,EMP-0046,2025-09-30,D01,R007,4,Pune,Remote,Permanent,M.Tech,...,2,0.1448,0,0,master_employee_snapshot,NaT,NaT,NaN,NaN,NaN

In [395]:
# Train/test split

In [396]:
from sklearn.model_selection import train_test_split

In [397]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [398]:
X_train.shape

(1911, 36)

In [399]:
X_test.shape

(478, 36)

In [400]:
y_train.shape

(1911,)

In [401]:
y_test.shape

(478,)

In [402]:
#preprocessing pipeline

In [403]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [404]:
#numerical column

In [405]:
numeric_pipeline=Pipeline([("imputer",SimpleImputer(strategy="median")),
                           ("encoder",StandardScaler())
                          ])

In [406]:
categorical_pipeline=Pipeline([("imputer",SimpleImputer(strategy="most_frequent")),
                               ("encoder",OneHotEncoder(handle_unknown="ignore"))
                              ])

In [407]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num",numeric_pipeline,numeric_columns),
        ("cat",categorical_pipeline,categorical_columns)],remainder="drop")

In [408]:
X_train_processed=preprocessor.fit_transform(X_train)
X_test_processed=preprocessor.transform(X_test)

In [409]:
print("Processed training rows:", X_train_processed.shape[0])

Processed training rows: 1911

In [410]:
print("Processed testing rows:", X_test_processed.shape[0])

Processed testing rows: 478

In [411]:
len(y_train)

1911

In [412]:
len(y_test)

478

In [413]:
from scipy import sparse
if sparse.issparse(X_train_processed):
    train_missing = np.isnan(X_train_processed.data).sum()
else:
    train_missing = np.isnan(X_train_processed).sum()
if sparse.issparse(X_test_processed):
    test_missing = np.isnan(X_test_processed.data).sum()
else:
    test_missing = np.isnan(X_test_processed).sum()
print("Missing values in processed training data:", train_missing)
print("Missing values in processed testing data:", test_missing)

Missing values in processed training data: 0
Missing values in processed testing data: 0

In [414]:
feature_names = preprocessor.get_feature_names_out()
len(feature_names)
print("\nFirst 20 processed feature names:")

for name in feature_names[:20]:
    print(name)

First 20 processed feature names:
num__job_level
num__tenure_months
num__total_experience_years
num__previous_employers_count
num__commute_distance_km
num__annual_fixed_pay
num__comp_ratio
num__raises_received
num__last_raise_pct
num__months_since_last_raise
num__promotions_received
num__months_since_last_promotion
num__internal_transfers
num__last_performance_rating
num__last_engagement_score
num__manager_changes_12m
num__training_hours_12m
num__attendance_rate_3m
num__late_arrivals_3m
num__avg_overtime_hours_per_month_3m

In [415]:
# save the fitted preprocessing

In [416]:
import joblib

In [417]:
model_dir=Path("models")

In [418]:
model_dir.mkdir(parents=True, exist_ok=True)

In [419]:
joblib.dump(preprocessor, model_dir / "attrition_preprocessor.joblib")

['models/attrition_preprocessor.joblib']

In [420]:
print("Path:", model_dir / "attrition_preprocessor.joblib")

Path: models/attrition_preprocessor.joblib

In [421]:
# Create Metadata

In [422]:
import json

In [423]:
metadata={
        "pipeline_name":"cortexhr_attrition",
        "version":"features-1.0.0",
        "target_column":target,
        "input_feature_count":X.shape[1],
        "processed_feature_count":len(feature_names),
        "numeric_feature_count":len(numeric_columns),
        "categorial_feature_count":len(categorical_columns)
}

In [424]:
metadata_path=model_dir/"metadata.json"
with open(metadata_path,"w",encoding="utf-8") as file:
    json.dump(metadata,file,indent=4)

In [425]:
metadata_path

PosixPath('models/metadata.json')

In [426]:
json.dumps(metadata,indent=4)

'{\n    "pipeline_name": "cortexhr_attrition",\n    "version": "features-1.0.0",\n    "target_column": "left_within_12m",\n    "input_feature_count": 36,\n    "processed_feature_count": 136,\n    "numeric_feature_count": 30,\n    "categorial_feature_count": 6\n}'

In [427]:
loaded_preprocessor = joblib.load(
    model_dir / "attrition_preprocessor.joblib"
)

X_test_reloaded = loaded_preprocessor.transform(X_test)

if sparse.issparse(X_test_processed):
    difference = (X_test_reloaded - X_test_processed).data
    is_repeatable = np.allclose(difference, 0)
else:
    is_repeatable = np.allclose(
        X_test_reloaded,
        X_test_processed
    )

print("Output shape:", X_test_reloaded.shape)
is_repeatable

Output shape: (478, 136)

True

In [428]:
# Testing the pipeline

In [429]:
assert X_train_processed.shape[0]==X_train.shape[0]
assert X_test_processed.shape[0]==X_test.shape[0]
assert len(y_train)==X_train_processed.shape[0]
assert len(y_test)==X_test_processed.shape[0]

def missing_values(data):
    if sparse.issparse(data):
        return np.isnan(data.data).any()
    return np.isnan(data).any()
assert not missing_values(X_train_processed)
assert not missing_values(X_test_processed)

assert np.allclose(
    (X_test_reloaded - X_test_processed).data
    if sparse.issparse(X_test_processed)
    else X_test_reloaded - X_test_processed,0)

In [430]:

from pathlib import Path

PROJECT_DIR = Path.cwd()

folders = [
    "cortexhr_features",
    "cortexhr_features/transformers",
    "tests",
    "reports"
]

for folder in folders:
    path = PROJECT_DIR / folder
    path.mkdir(parents=True, exist_ok=True)
    print(f"Ready: {path}")

Ready: /workspace/cortexhr_features
Ready: /workspace/cortexhr_features/transformers
Ready: /workspace/tests
Ready: /workspace/reports

In [431]:
package_dir = Path("cortexhr_features")
transformers_dir = package_dir / "transformers"

In [432]:
(package_dir / "__init__.py").touch(exist_ok=True)
(transformers_dir / "__init__.py").touch(exist_ok=True)

In [433]:
import pandas as pd
from pathlib import Path

file_path = Path("/workspace/data/raw/02_CortexHR_AI_ML_Dataset.xlsx")

print("Workbook exists:", file_path.exists())

if file_path.exists():
    excel = pd.ExcelFile(file_path)
    print("\nAvailable sheets:")
    for sheet in excel.sheet_names:
        print("-", sheet)
else:
    print("Workbook not found at this path.")

Workbook exists: True

Available sheets:
- README
- data_dictionary
- attrition_dataset
- protected_attributes
- attrition_scoring_2026
- engagement_survey
- performance_reviews
- attendance_monthly_features
- attendance_anomaly_labels
- attendance_daily_examples
- payroll_monthly_features
- payroll_anomaly_labels
- monthly_headcount_history
- workforce_events
- salary_training
- job_descriptions
- resumes
- resume_job_labels
- resume_bias_pairs
- resume_protected_attrs
- chatbot_nlu_training
- chatbot_test_set
- chatbot_responses
- hr_faq
- chatbot_dialogues
- baseline_benchmarks
- anomaly_baselines
- sample_attrition_risk
- sample_anomaly_results
- sample_forecast
- answer_key_planted_dirt
- answer_key_notes

In [434]:
import pandas as pd

# Work on copies; preserve the original datasets
attrition_base = df.copy()
attendance_base = df1.copy()
payroll_base = df2_clean.copy()

# Ensure date columns use datetime
attrition_base["observation_date"] = pd.to_datetime(
    attrition_base["observation_date"], errors="coerce"
)
attendance_base["month"] = pd.to_datetime(
    attendance_base["month"], errors="coerce"
)
payroll_base["month"] = pd.to_datetime(
    payroll_base["month"], errors="coerce"
)

# Keep only attendance and payroll fields that can be aggregated.
# Do not use employee IDs, payroll item IDs, or run IDs as features.
attendance_cols = [
    c for c in attendance_base.select_dtypes(include="number").columns
    if c != "employee_id"
]
payroll_cols = [
    c for c in payroll_base.select_dtypes(include="number").columns
    if c != "employee_id"
]

# Join monthly records to each employee's observation date.
# Only months on or before the observation date are eligible.
def summarize_last_3_months(observations, monthly, value_cols, prefix):
    result = observations[["employee_id", "observation_date"]].copy()
    result["_row_id"] = range(len(result))

    monthly = monthly.dropna(
        subset=["employee_id", "month"]
    ).copy()

    # Avoid using duplicate employee-month records more than once.
    # Numeric values are aggregated by month before selecting the latest 3 months.
    monthly = (
        monthly.groupby(["employee_id", "month"], as_index=False)[value_cols]
        .mean()
    )

    merged = result.merge(
        monthly,
        on="employee_id",
        how="left"
    )

    merged = merged[
        merged["month"].isna()
        if "month" in merged.columns else
        merged["observation_date"].isna()
    ] if False else merged

    return merged

print("Numeric attendance columns:", attendance_cols)
print("Numeric payroll columns:", payroll_cols)

Numeric attendance columns: ['job_level', 'scheduled_days', 'present_days', 'wfh_days', 'half_days_unpaid', 'paid_leave_days', 'unpaid_absence_days', 'longest_unpaid_streak_days', 'late_arrivals', 'avg_hours_worked', 'overtime_hours', 'attendance_rate']
Numeric payroll columns: ['job_level', 'monthly_fixed_gross', 'payable_days', 'lop_days', 'overtime_hours_paid', 'overtime_pay', 'variable_pay', 'gross_pay', 'pf_employee', 'esi_employee', 'professional_tax', 'tds', 'other_deductions', 'total_deductions', 'net_pay']

In [435]:
# Inspect monthly date conventions
print("Attendance month examples:")
print(
    attendance_base[["employee_id", "month"]]
    .drop_duplicates()
    .sort_values("month")
    .head(10)
    .to_string(index=False)
)

print("\nPayroll month examples:")
print(
    payroll_base[["employee_id", "month"]]
    .drop_duplicates()
    .sort_values("month")
    .head(10)
    .to_string(index=False)
)

# Check row preservation and feature coverage
attendance_features = [
    c for c in attrition_integrated.columns
    if c.startswith("attendance_")
]
payroll_features = [
    c for c in attrition_integrated.columns
    if c.startswith("payroll_")
]

print("\nRow count preserved:", len(attrition_integrated) == len(attrition_base))
print("Attendance features:", len(attendance_features))
print("Payroll features:", len(payroll_features))
print(
    "Rows with any attendance data:",
    attrition_integrated[attendance_features].notna().any(axis=1).sum()
)
print(
    "Rows with any payroll data:",
    attrition_integrated[payroll_features].notna().any(axis=1).sum()
)

Attendance month examples:
employee_id      month
   EMP-0002 2025-04-01
   EMP-0256 2025-04-01
   EMP-0049 2025-04-01
   EMP-0550 2025-04-01
   EMP-0259 2025-04-01
   EMP-0549 2025-04-01
   EMP-0261 2025-04-01
   EMP-0548 2025-04-01
   EMP-0265 2025-04-01
   EMP-0266 2025-04-01

Payroll month examples:
employee_id      month
   EMP-0002 2025-04-01
   EMP-0463 2025-04-01
   EMP-0461 2025-04-01
   EMP-0460 2025-04-01
   EMP-0459 2025-04-01
   EMP-0458 2025-04-01
   EMP-0457 2025-04-01
   EMP-0456 2025-04-01
   EMP-0454 2025-04-01
   EMP-0453 2025-04-01

Row count preserved: True
Attendance features: 12
Payroll features: 14
Rows with any attendance data: 2389
Rows with any payroll data: 389

In [445]:
print("Observation date range:")
print(attrition_base["observation_date"].min())
print(attrition_base["observation_date"].max())

print("\nAttendance monthly range:")
print(attendance_base["month"].min())
print(attendance_base["month"].max())

print("\nPayroll monthly range:")
print(payroll_base["month"].min())
print(payroll_base["month"].max())

print("\nObservation dates and eligible monthly records:")
for date in sorted(attrition_base["observation_date"].dropna().unique())[:10]:
    date = pd.Timestamp(date)
    print(
        date.date(),
        "| latest eligible calendar month:",
        date.to_period("M")
    )

Observation date range:
2021-01-01 00:00:00
2025-09-30 00:00:00

Attendance monthly range:
2025-04-01 00:00:00
2026-09-01 00:00:00

Payroll monthly range:
2025-04-01 00:00:00
2026-09-01 00:00:00

Observation dates and eligible monthly records:
2021-01-01 | latest eligible calendar month: 2021-01
2021-01-03 | latest eligible calendar month: 2021-01
2021-01-04 | latest eligible calendar month: 2021-01
2021-01-05 | latest eligible calendar month: 2021-01
2021-01-07 | latest eligible calendar month: 2021-01
2021-01-08 | latest eligible calendar month: 2021-01
2021-01-09 | latest eligible calendar month: 2021-01
2021-01-10 | latest eligible calendar month: 2021-01
2021-01-11 | latest eligible calendar month: 2021-01
2021-01-13 | latest eligible calendar month: 2021-01

In [446]:
# Keep only monthly feature columns that exist in the integrated dataset
monthly_attendance_cols = [
    f"attendance_{c}"
    for c in attendance_cols
    if f"attendance_{c}" in attrition_integrated_safe.columns
]

monthly_payroll_cols = [
    f"payroll_{c}"
    for c in payroll_cols
    if f"payroll_{c}" in attrition_integrated_safe.columns
]

early_mask = (
    attrition_integrated_safe["observation_date"]
    < pd.Timestamp("2025-04-01")
)

print("Original rows:", len(attrition_base))
print("Integrated rows:", len(attrition_integrated_safe))
print("Rows preserved:", len(attrition_integrated_safe) == len(attrition_base))

print("\nPre-April 2025 observations:", early_mask.sum())

print(
    "Early rows with monthly attendance values:",
    attrition_integrated_safe.loc[
        early_mask, monthly_attendance_cols
    ].notna().any(axis=1).sum()
)

print(
    "Early rows with monthly payroll values:",
    attrition_integrated_safe.loc[
        early_mask, monthly_payroll_cols
    ].notna().any(axis=1).sum()
)

Original rows: 2389
Integrated rows: 2389
Rows preserved: True

Pre-April 2025 observations: 2000
Early rows with monthly attendance values: 0
Early rows with monthly payroll values: 0

In [447]:
sys.path.insert(0, "/workspace/src")
from feature import add_attrition_features
from features import build_pipeline
df_final = add_attrition_features(attrition_integrated_safe)

target = "left_within_12m"

excluded_columns = [
    "row_id",
    "employee_id",
    "observation_date",
    "source",
    "voluntary_left_within_12m",
    "exit_date",
    "resignation_date",
    "exit_reason",
    "exit_interview_done",
    "fnf_settlement_amount",
    target,
]
X_final = df_final.drop(columns=excluded_columns, errors="ignore")
y_final = df_final[target].copy()

numeric_columns = X_final.select_dtypes(include="number").columns.tolist()
categorical_columns = X_final.select_dtypes(
    include=["object", "category", "string"]
).columns.tolist()
X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(
    X_final,
    y_final,
    test_size=0.2,
    random_state=42,
    stratify=y_final,
)
pipeline = build_pipeline(numeric_columns, categorical_columns)
pipeline.fit(X_train_final)
three_rows_output = pipeline.transform(X_train_final.iloc[:3])
assert three_rows_output.shape[0] == 3
assert target not in X_final.columns
assert not (set(excluded_columns) - {target}) & set(X_final.columns)
has_missing = (
    np.isnan(three_rows_output.data).any()
    if sparse.issparse(three_rows_output)
    else np.isnan(three_rows_output).any()
)
assert not has_missing
print("Integrated dataset rows:", len(df_final))
print("Input feature columns:", X_final.shape[1])
print("Numeric columns:", len(numeric_columns))
print("Categorical columns:", len(categorical_columns))
print("Three-row transformed shape:", three_rows_output.shape)
print("Target excluded:", target not in X_final.columns)
print("Missing values in output:", has_missing)
print("PIPELINE TEST PASSED")

Integrated dataset rows: 2389
Input feature columns: 61
Numeric columns: 55
Categorical columns: 6
Three-row transformed shape: (3, 161)
Target excluded: True
Missing values in output: False
PIPELINE TEST PASSED

In [ ]:
'''Explanation of the three-row test
In this step, I tested the preprocessing pipeline using three rows from the training dataset. The pipeline converts the raw input data into a numerical format that can be used by a machine learning model.

Since the pipeline was already fitted on the training data, these three rows were transformed using the same imputation values, scaling parameters, and category encodings. This ensures that the test uses the existing preprocessing rules rather than learning new ones.

I displayed the first 10 transformed features to check how the raw data looks after preprocessing. I also verified that exactly three rows were transformed, the target column (left_within_12m) was not used as an input, and all output values were finite with no missing or invalid numerical values.

The test passed successfully, confirming that the reusable preprocessing pipeline produces model-ready numerical data for the three input rows.'''

In [448]:
from pathlib import Path

output_path = Path("/workspace/data/processed")
output_path.mkdir(parents=True, exist_ok=True)

df_final.to_csv(
    output_path / "attrition_features.csv",
    index=False
)

print("Saved dataset shape:", df_final.shape)
print("Target available:", "left_within_12m" in df_final.columns)

Saved dataset shape: (2389, 72)
Target available: True